"""initial migration

Revision ID: e55a1d36393a
Revises: 
Create Date: 2022-03-07 12:03:39.480598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e55a1d36393a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productsales', 'prod_code',
               existing_type=mysql.VARCHAR(length=8),
               nullable=True)
    op.alter_column('productsales', 'employee_id',
               existing_type=mysql.VARCHAR(length=7),
               nullable=True)
    op.alter_column('productsales', 'year_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('productsales', 'week',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('productsales', 'quantity_prodsold',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('warrantysales', 'esp_code',
               existing_type=mysql.VARCHAR(length=7),
               nullable=True)
    op.alter_column('warrantysales', 'employee_id',
               existing_type=mysql.VARCHAR(length=7),
               nullable=True)
    op.alter_column('warrantysales', 'year_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('warrantysales', 'week',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('warrantysales', 'quantity_espsold',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('workweek', 'week',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('workweek', 'year_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('workyear', 'year',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workyear', 'year',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('workweek', 'year_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('workweek', 'week',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('warrantysales', 'quantity_espsold',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('warrantysales', 'week',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('warrantysales', 'year_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('warrantysales', 'employee_id',
               existing_type=mysql.VARCHAR(length=7),
               nullable=False)
    op.alter_column('warrantysales', 'esp_code',
               existing_type=mysql.VARCHAR(length=7),
               nullable=False)
    op.alter_column('productsales', 'quantity_prodsold',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('productsales', 'week',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('productsales', 'year_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('productsales', 'employee_id',
               existing_type=mysql.VARCHAR(length=7),
               nullable=False)
    op.alter_column('productsales', 'prod_code',
               existing_type=mysql.VARCHAR(length=8),
               nullable=False)
    # ### end Alembic commands ###
